// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarTracker.Infrastructure.Persistence;

#nullable disable

namespace SolarTracker.Infrastructure.Migrations
{
    [DbContext(typeof(SolarTrackerDbContext))]
    [Migration("20260511184500_AddSolarPanelOptimizationAutomation")]
    partial class AddSolarPanelOptimizationAutomation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.CurrentMeasuringUnitDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GpioPin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SolarPanelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SolarPanelId")
                        .IsUnique();

                    b.ToTable("CurrentMeasuringUnits", (string)null);
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.InstallationSiteDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InstallationSites", (string)null);
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.LinearMotorDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveDownGpioPin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveUpGpioPin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SolarPanelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SolarPanelId");

                    b.ToTable("LinearMotors", (string)null);
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstallationSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationSiteId");

                    b.ToTable("SolarPanels", (string)null);
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.SolarOptimizationScheduleConfigurationDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SolarOptimizationScheduleConfigurations", (string)null);
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelOptimizationStateDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SolarPanelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SolarPanelId")
                        .IsUnique();

                    b.ToTable("SolarPanelOptimizationStates", (string)null);
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.SolarTrackingConfigurationDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAdjustmentSteps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PositionThresholdDegrees")
                        .HasColumnType("REAL");

                    b.Property<int>("SolarPanelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepDurationMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SolarPanelId")
                        .IsUnique();

                    b.ToTable("SolarTrackingConfigurations", (string)null);
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.TiltMeasuringUnitDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GpioPin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SolarPanelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SolarPanelId")
                        .IsUnique();

                    b.ToTable("TiltMeasuringUnits", (string)null);
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.CurrentMeasuringUnitDb", b =>
                {
                    b.HasOne("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelDb", "SolarPanel")
                        .WithOne("CurrentMeasuringUnit")
                        .HasForeignKey("SolarTracker.Infrastructure.Persistence.Entities.CurrentMeasuringUnitDb", "SolarPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarPanel");
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.LinearMotorDb", b =>
                {
                    b.HasOne("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelDb", "SolarPanel")
                        .WithMany("LinearMotors")
                        .HasForeignKey("SolarPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarPanel");
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelDb", b =>
                {
                    b.HasOne("SolarTracker.Infrastructure.Persistence.Entities.InstallationSiteDb", "InstallationSite")
                        .WithMany("SolarPanels")
                        .HasForeignKey("InstallationSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstallationSite");
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelOptimizationStateDb", b =>
                {
                    b.HasOne("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelDb", "SolarPanel")
                        .WithOne()
                        .HasForeignKey("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelOptimizationStateDb", "SolarPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarPanel");
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.SolarTrackingConfigurationDb", b =>
                {
                    b.HasOne("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelDb", "SolarPanel")
                        .WithOne("SolarTrackingConfiguration")
                        .HasForeignKey("SolarTracker.Infrastructure.Persistence.Entities.SolarTrackingConfigurationDb", "SolarPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarPanel");
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.TiltMeasuringUnitDb", b =>
                {
                    b.HasOne("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelDb", "SolarPanel")
                        .WithOne("TiltMeasuringUnit")
                        .HasForeignKey("SolarTracker.Infrastructure.Persistence.Entities.TiltMeasuringUnitDb", "SolarPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarPanel");
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.InstallationSiteDb", b =>
                {
                    b.Navigation("SolarPanels");
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelDb", b =>
                {
                    b.Navigation("SolarTrackingConfiguration");

                    b.Navigation("TiltMeasuringUnit");

                    b.Navigation("CurrentMeasuringUnit");

                    b.Navigation("LinearMotors");
                });
#pragma warning restore 612, 618
        }
    }
}
