// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarTracker.Infrastructure.Persistence;

#nullable disable

namespace SolarTracker.Infrastructure.Migrations
{
    [DbContext(typeof(SolarTrackerDbContext))]
    partial class SolarTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.InstallationSiteDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InstallationSites", (string)null);
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.LinearMotorDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstallationSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationSiteId");

                    b.ToTable("LinearMotors", (string)null);
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstallationSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationSiteId");

                    b.ToTable("SolarPanels", (string)null);
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.LinearMotorDb", b =>
                {
                    b.HasOne("SolarTracker.Infrastructure.Persistence.Entities.InstallationSiteDb", "InstallationSite")
                        .WithMany("LinearMotors")
                        .HasForeignKey("InstallationSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstallationSite");
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.SolarPanelDb", b =>
                {
                    b.HasOne("SolarTracker.Infrastructure.Persistence.Entities.InstallationSiteDb", "InstallationSite")
                        .WithMany("SolarPanels")
                        .HasForeignKey("InstallationSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstallationSite");
                });

            modelBuilder.Entity("SolarTracker.Infrastructure.Persistence.Entities.InstallationSiteDb", b =>
                {
                    b.Navigation("LinearMotors");

                    b.Navigation("SolarPanels");
                });
#pragma warning restore 612, 618
        }
    }
}
